package com.task.kamrul.entity;
// Generated Jan 26, 2021 8:17:01 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private int itemId;
     private String itemName;
     private Date itemDate;
     private String itemDesc;

    public Item() {
    }

	
    public Item(int itemId, String itemName, Date itemDate) {
        this.itemId = itemId;
        this.itemName = itemName;
        this.itemDate = itemDate;
    }
    public Item(int itemId, String itemName, Date itemDate, String itemDesc) {
       this.itemId = itemId;
       this.itemName = itemName;
       this.itemDate = itemDate;
       this.itemDesc = itemDesc;
    }
   
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public Date getItemDate() {
        return this.itemDate;
    }
    
    public void setItemDate(Date itemDate) {
        this.itemDate = itemDate;
    }
    public String getItemDesc() {
        return this.itemDesc;
    }
    
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }




}


